packages:
  - name: ace
    main: ace
    location: 'lib/ace'
  - name: ace/keyboard/vim
    main: vim
    location: 'lib/ace'
modules:
  - name: application
  - name: posts
  - name: form
  - name: renderer
  - name: more-responsive-less-ui
